# Generated by Django 3.1.14 on 2023-06-05 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20230605_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 5, 14, 10, 19, 330369, tzinfo=utc), verbose_name='Время оживления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 5, 14, 10, 19, 330436, tzinfo=utc), verbose_name='Время исчезновения'),
        ),
    ]
